services:
  caddy:
    ports:
      - ${CADDY_PORT}:80
    volumes:
      - ./:/var/www/app

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  php:
    build:
      target: php_dev
    volumes:
      - ./:/var/www/app

  mercure:
    ports:
      - ${MERCURE_PORT}:80
    environment:
      SERVER_NAME: ':80'
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

