name: ${PROJECT_NAME}

services:
  caddy:
    image: ${PROJECT_NAME}_caddy
    container_name: ${PROJECT_NAME}_caddy
    build:
      target: caddy
    depends_on:
      - php
    

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: ${PROJECT_NAME}_postgres
    environment:
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${PROJECT_NAME}", "-U", "${PROJECT_NAME}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_php
    build:
      target: php_dev
    depends_on:
      - postgres

  mercure:
    image: dunglas/mercure
    container_name: ${PROJECT_NAME}_mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  database_data:
  mercure_data:
  mercure_config:
