services:
  caddy:
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/app

  postgres:
    ports:
      - 5433:5432

  php:
    build:
      target: php_dev
    entrypoint: ["/var/www/app/docker/entrypoint.dev.sh"]

  mercure:
    ports:
      - 7000:80
    environment:
      SERVER_NAME: ':80'
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

