name: gaia

services:
  caddy:
    image: gaia_caddy
    container_name: gaia_caddy
    build:
      target: caddy
    depends_on:
      - php
    

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: gaia_postgres
    environment:
      POSTGRES_DB: gaia
      POSTGRES_USER: gaia
      POSTGRES_PASSWORD: gaia_pwd
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "gaia", "-U", "gaia" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    image: gaia_php
    container_name: gaia_php
    build:
      target: php_dev
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/app

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: gaia_mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  database_data:
  mercure_data:
  mercure_config:
