services:
  caddy:
    ports:
      - ${SERVER_PORT}:80

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  mercure:
    ports:
      - ${MERCURE_PORT}:80
    environment:
      SERVER_NAME: ':80'
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

