version: "3.4"

services:
  caddy:
    ports:
      - ${SERVER_PORT}:80

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  mercure:
    ports:
      - ${MERCURE_PORT}:80
    environment:
      SERVER_NAME: ':80'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev

